### ISSUE TITLE
Lazy loading commands

### ISSUE THREAD

**Issue by michalbundyra** [michalbundyra/laminas-cli#2]
We'd like to provide some layer for lazy loading commands in out cli application,
so that we do not need load all dependencies for all registered commands on listing commands, etc.

Probably we can provide some wrapper and use static `getDefaultName` method on command.

Should be investigated more and implemented accordingly.

I think it is not the highest priority and can be done in the next minor release.

**Comment by kynx** [comment]
Would https://symfony.com/doc/current/console/lazy_commands.html get us anywhere?

Great to see this project, BTW :)

**Comment by michalbundyra** [comment]
@kynx Nice one, thanks! We have to try, but it looks promising 👍
