### ISSUE TITLE
Examples of usage

### ISSUE THREAD

**Issue by divix1988** [michalbundyra/laminas-cli#5]
Are there any example scripts which would show how to create any custom plugins via laminas-cli?

**Comment by michalbundyra** [comment]
@divix1988 Not sure what you mean. The package is not yet complete and we can create it any way we want.

Have you seen [notes in README.md](https://github.com/michalbundyra/laminas-cli#custom-command)?

If you are asking about something else, please clarify your question.

**Comment by divix1988** [comment]
Yes I've seen the notes.

I wasn't aware it's unfinished component. I will look forward for the end results.

BTW would you mind if I will outline your component in the book?

**Comment by michalbundyra** [comment]
@divix1988 

> I wasn't aware it's unfinished component. I will look forward for the end results.

I've started it last week but I had this idea for a long time in my head.

> BTW would you mind if I will outline your component in the book?

No problem, but please remember that it is uncompleted, and even non-usable component right now.
The plan is to move it into [Laminas organisation](https://github.com/laminas) and update other components to use it.

Also, please remember that we might the way we configure the component, etc.
You can see other tickets I've created in the repo, to see what I want to achieve and where we are now.

Thanks!
